#!/bin/bash
CURRENT=$(df /home | grep / | awk '{ print $5}' | sed 's/%//g')
THRESHOLD=98

if [ "$CURRENT" -gt "$THRESHOLD" ] ; then
    mail -s 'Disk Space Alert' mrdavidyosef@gmail.com << EOF
Your root partition remaining free space is critically low. Used: $CURRENT%
EOF
fi

