#!/bin/bash

# Eitest investigation script
# https://www.abuseat.org
# https://sitecheck.sucuri.net/

# Watch for connections to sinkhole
 connect=$(ss -antp | grep 192.42.119.41);

# If connection found then capture data
  if [[ $connect ]]; then

   # Get pid from connection
   PID=$(echo $connect | grep -Eio "pid=[0-9]{1,}" | cut -d= -f2);
 
   # Strace pid
   (strace -yrTfs 1024 -e trace=sendto,connect,open,write -o strace-$PID.out -p $PID &)

   # Log some basic info about the connection and process
   ps aux | awk "(\$2 ~ /$PID/)"'{print $0}' >> /root/connect-log.txt;
   echo $connect >> /root/connect-log.txt;
 fi

echo `date`

exit 0
